version: "3.9"

services:
  mongo:
    image: mongo
    container_name: private-journal-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: private-journal-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo

volumes:
  mongo-data:
